services:
  - type: web
    name: fastapi-pdf-translator
    env: python
    buildCommand: |
      apt-get update && apt-get install -y libreoffice
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
